[package]
name = "webmdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "3", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
xml-rs = "0.8"
convert_case = "0.5"

[dev-dependencies]
insta = { version = "1.18.1", features = ["yaml"] }

[profile.release]
strip = true
