name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: llvm-tools-preview

    - name: Install grcov
      run: if [[ ! -e ~/.cargo/bin/grcov ]]; then cargo install grcov; fi

    - name: Run tests
      run: cargo test
      env:
        RUSTFLAGS: '-C instrument-coverage'
        LLVM_PROFILE_FILE: 'report-%p-%m.profraw'

    - name: Run grcov
      run: grcov . --binary-path target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
